### ISSUE TITLE
Switch to using beta list of variants

### ISSUE THREAD

**Issue by rcurrie** [BRCAChallenge/literature-search#21]
Currently we pull the list of variants by extracting 

output/release/built_with_change_types.tsv

from

https://brcaexchange.org/backend/downloads/releases/current_release.tar.gz

@zfisch If we ingest literature.json into production and it has variants that are new will the ingest just ignore them? If so then I can switch to gathering the variants list from beta if you provide the URL.

**Comment by zfisch** [comment]
If a variant is in the literature results but not in the database, it will still add new VariantPaper objects for that variant. This shouldn't be a problem because the hg38 is just a text field and not a foreign key:

Here's the model:
```
class VariantPaper(models.Model):
    variant_hg38 = models.TextField()
    paper = models.ForeignKey(Paper)
    mentions = ArrayField(models.TextField())
    points = models.IntegerField(default=0)
    deleted = models.BooleanField()
```

Here's the save:
```
vp = VariantPaper(variant_hg38=variant_genomic_coordinate, paper=paper, points=points, mentions=mentions, deleted=False)
```

Here's the lookup:
```
variant_name = variant.Genomic_Coordinate_hg38
variantpapers = VariantPaper.objects.select_related('paper').filter(variant_hg38=variant_name).all()
```

**Comment by rcurrie** [comment]
Sounds good - I'll switch then to the beta build, what's the equivalent URL for that:

https://brcaexchange.org/backend/downloads/releases/current_release.tar.gz

but on beta?

**Comment by zfisch** [comment]
http://brcaexchange-prod.gi.ucsc.edu/backend/downloads/releases/current_release.tar.gz

notice we don't currently have an ssl cert for beta
