### ISSUE TITLE
Manual QC of papers that are downloaded but fail to generate any mentions

### ISSUE THREAD

**Issue by rcurrie** [BRCAChallenge/literature-search#8]
Creating an issue to track manually looking at random papers that are downloaded but fail to generate any mention.

**Comment by rcurrie** [comment]
# 1311530
Article about 'BrcAMP', not 'BRCA'

...d in the isolated-per- fused rat lung using a PKA inhibitor, &-CAMPS, &bromo- CAMP (&BrcAMP), and the diterpene
activator of adenylate cyclase (AC), forskolin (FSK). A role for K’ channels was also assessed with the nonselectiv
e K+ channel...

- [ ] Search for only BRCA, BRCA1, or BRCA2 in title or abstract, but another article has '...including p53 and BRCA1/2...'_

**Comment by rcurrie** [comment]
# 11237519
Crawler only able to download first page pdf which didn't include any variant mentions

**Comment by rcurrie** [comment]
# 15606925
Article about gene expression and doesn't include any mention of variants

_Identification of a three-gene expression signature of poor-prognosis breast carcinoma_

**Comment by rcurrie** [comment]
# 18094425
Article about gene expression, no mention of variants. 

_BRCA1 mRNA Expression Levels Predict for Overall Survival in Ovarian Cancer after Chemotherapy_

Couple of DNA sequences in the paper but all were in reference to primer sequences

**Comment by rcurrie** [comment]
# 20615754
Only able to download abstract

**Comment by rcurrie** [comment]
# 22880466
Article doesn't have BRCA anywhere, including title and abstract. Net of that there doesn't appear to be any variants mentioned either.

- [ ] Verify that BRCA is in the title or abstract beyond what we are depending on with the PMID query in get-pubs

**Comment by rcurrie** [comment]
# 25023546
Article about surgical outcomes for BRCA1/2 mutation carriers. No specific mention of any particular variant

**Comment by rcurrie** [comment]
# 26902145
Article about BRCA1 activation by SIRT1, no mention of any variants

**Comment by rcurrie** [comment]
# 28721278
Article about pathways and radiation exposure, no mention of variants

- [ ] Verify the DNA/RNA sequences were flagged by 'find'

**Comment by rcurrie** [comment]
# 30386115
Article discusses clinical outcomes from loss, but all mentions appear to be about very large structural:

_One study revealed chromosome 9p21 deletion more frequently in pleural than in peritoneal tumors (85% vs. 36%), whereas 5p15 and 7p12 gains were more common in peritoneal than in pleural tumors_

**Comment by rcurrie** [comment]
# 1708209
Article about BrcAMP

_In the presence of 8-BrcAMP during 6 h of perfusion, specific activity of “‘S- labeled SP-A in immunoprecipitated pro_

- [ ] Narrow selection of PMID search

**Comment by rcurrie** [comment]
# 11016625
Article about Phosphorylation of BRCA1 after damage/radation. No mentions of specific variants.

**Comment by rcurrie** [comment]
# 15126609
Correspondance about BRCA1 germline mutations, but no variants mentioned - only other gene expression markers

**Comment by rcurrie** [comment]
# 17301256
Article about Sociocultural predictors of breast cancer, no mention of specific variants

**Comment by rcurrie** [comment]
# 19671842 
Article about CIP2A and aggressivity of breast cancer, no mention of specific variants

**Comment by rcurrie** [comment]
# 21829373
Article about telomere shortening and associated telomere maintenance gene's as indicators of genomic instability.

**Comment by rcurrie** [comment]
# 23825307
Paper about maternal disclosure of BRCA1/2, no variants mentioned

**Comment by rcurrie** [comment]
# 30386115
Discussed mesothelioma and mutations in various genes but no mention of any specific mutation

**Comment by rcurrie** [comment]
# 22880466
BRCA not mentioned anywhere in the paper

- [x] QC/refine PMID candidate search

Abstract in pdf differs from online which is why it was included in the list of PMID candidates.

**Comment by rcurrie** [comment]
# 28721278
Paper about micro RNA's and BRCA1 among other items, no specific variants mentioned

**Comment by rcurrie** [comment]
@amycoffin @zfisch @melissacline Reviewed 20 random papers that failed to yield any mentions and none of them had any variants in them. Preliminarily concluding the drop from 14186 downloaded to 2227 with mentions is due to papers not mentioning variants.

**Comment by strbean** [comment]
Just popping in to note: some papers just plain won't convert from PDF to
plain text with available tools, so that probably accounts for another
chunk.
