### ISSUE TITLE
Compare output of crawler to LOVD truth set

### ISSUE THREAD

**Issue by rcurrie** [BRCAChallenge/literature-search#9]
Normalize the LOVD truth set from https://github.com/amycoffin/litSearchTruthsetTesting so it can be compared against the output of the crawler.

**Comment by rcurrie** [comment]
@amycoffin Take a look at [lovd-normalized](https://github.com/BRCAChallenge/pubMunch-BRCA/blob/master/tests/lovd-normalized.tsv) which is the result of running tests/normalize_lovd.py on the two .tab files. I've only processed rows that have a Variant/DNA that starts with 'c.'. I can add additional logic to try and get some of the other rows but it might be better to hand fix the ones that are missing the c.

**Comment by amycoffin** [comment]
@rcurrie I used the lovd-normalized to get a data structure that can produce numbers like this:

variants in litsearch for 12531920 pmid:
41
variants in lovd for 12531920 pmid:
39
number of matches between the the two:
37

Not sure what the best overall stats to run are, but we have progress here that we can discuss in our meeting soon.

**Comment by rcurrie** [comment]
@amycoffin I added a pyhgvs_Genomic_Coordinate_38 column to the [lovd-normalized.tsv](https://github.com/BRCAChallenge/pubMunch-BRCA/blob/master/tests/lovd-normalized.tsv) file for convenience so its keyed the same way as literature.json

**Comment by amycoffin** [comment]
@rcurrie per our meeting, I will look at percentages that represent performance for each paper, with a median/mean for those, and get some overall performance numbers

**Comment by amycoffin** [comment]
@rcurrie there is still a slight difference between the two, but im still getting data using a few lines of parsing so don't worry too much:

litsearch json: chr17:g.43106501:T>C
lovd: chr13:g.43106501T>C

**Comment by amycoffin** [comment]
@melissacline @rcurrie 
Here is a histogram of performance ratios per paper (10 bins, corresponding total values below). 119 total papers. I used a filter to make sure that a PMID was in the json["papers"] layer prior to running stats.  

[litsearchperformancejan719](https://user-images.githubusercontent.com/25374391/50795323-db4d0700-129b-11e9-91c5-80dc1bdec9a6.png)

ratio = variants in litsearch set identical to lovd variants/ total found in lovd 

example: 

variants in litsearch for 15133503 pmid:
15
variants in lovd for 15133503 pmid:
24
number of matches between the the two:
12
ratio: 0.50 

I am still working on data that demonstrates the difference between found litsearch vars and found lovd vars per paper. 

119 unique papers common in LOVD and json
119 ratios calculated
median ratio 1.0
mean ratio 0.741428571429
standard deviation 0.374953858706
175 unique PMIDs in lovd-normalized
[ 17.   4.   2.   4.   0.   6.   4.   3.   6.  73.]

**Comment by rcurrie** [comment]
‘mean ratio0.74’

i.e. literature.json has 74% of what is in lovd-normalized?

or said differently ‘we found 74% of the lovd ground truth’?

**Comment by amycoffin** [comment]
@rcurrie that is just the mean of the 119 ratios. But considering that 73 ratios are 1.0, and 17 ratios are 0.0, I'm not sure the mean is all that helpful. I don't know how helpful it is to calculate overall numbers considering the spread, but I can.

**Comment by rcurrie** [comment]
So 73 are a perfect score, and 17 are complete fail - right?

**Comment by melissacline** [comment]
Encouraging!  If we take together all of the variants in all of the papers
in the LOVD truth set, how many are we finding?

**Comment by amycoffin** [comment]
@rcurrie actually there are 17 variants that fall between 0.0-0.10, and 73 variants that fall between 0.90-1.0. I can look for specific numbers. 
@melissacline there are 1780 total variants in the LOVD truth set, and 2331 variants in the LitSearch JSON associated with the same PMIDs found in the LOVD truth set. 

If these are all the numbers we need, I'm happy to polish everything up for git so that y'all can double check any logics I used. I was pretty thorough in making sure things were doing what I thought they were doing, though the code might be very unoptimized.

**Comment by amycoffin** [comment]
@rcurrie there are actually 13 complete fails, and 66 perfect scores

**Comment by melissacline** [comment]
What is the size of the Intersection between the json set and the LOVD set?

**Comment by amycoffin** [comment]
@melissacline The size of the intersection is 1039 variants.

**Comment by rcurrie** [comment]
@amycoffin Can you send or paste here the list of PMID's that are a complete fail? I'd like to spelunk into them a bit.

**Comment by amycoffin** [comment]
Here is the list of 13 'complete fail' PMIDs:
['19423647', '15353005', '24395671', '22144684', '11504767', '11185744', '18712473', '15345110', '12759930', '12442171', '14513821', '17899372', '10638982']

**Comment by rcurrie** [comment]
Diving down into 19423647 and I've discovered an error in the lovd.tsv I generated over the weekend - 949 of the rows have nan at the start of the pyhgvs_Genomic_Coordinate_38

@amycoffin  - if you're using that new field then my bad and let me debug what's going on.

For this paper specifically (19423647)

Crawler found and mapped 4 mentions:


NC_000013.11:g.32356462A>G | NM_000059.3:c.7470A>G | 19423647 | G>A mutation in exon 7 but the maintenance of ...
-- | -- | -- | --
NM_000059.3:c.7470A>G | 19423647 | G>A mutation in exon 7 but the maintenance of ...
NM_007299.3:c.859G>A | 19423647 | [1] reported on an Italian woman, affected wit...
NM_007298.3:c.859G>A | 19423647 | [1] reported on an Italian woman, affected wit...

and lovd has 2 entries:

1696	19423647	NM_000059.3:c.631G>A	NC_000013.11:g.32326613G>A	nan:g.32326613G>A
1970	19423647	NM_000059.3:c.7008-2A>T	NC_000013.11:g.32354859A>T	nan:g.32354859A>T

More after I get on the bus...

**Comment by rcurrie** [comment]
@amycoffin I fixed the bug in the lovd normalization and updated the [lovd-normalized](https://github.com/BRCAChallenge/pubMunch-BRCA/blob/master/tests/lovd-normalized.tsv) file. Can you re-run and see if the fails are improved?

**Comment by amycoffin** [comment]
@rcurrie I haven't used the updated version at all because of this discrepancy:

litsearch json: chr13:g.32363190:A>T (notice the : after the coordinate) 
lovd: chr13:g.32363190A>T (no : after the coordinate)

It was easier to just leave my older work-around in place than to use the new file.

**Comment by rcurrie** [comment]
@amycoffin Fixed the pyhgvs_Genomic_Coordinate_38 column

Here's my rough stats:

175 unique pmids and 1044 unique variants in LOVD truth set
119 common pmids to literature.json
750 common variants to literature.json

**Comment by melissacline** [comment]
Wow, that's really encouraging!  How many of the (1044 - 750) variants
we're missing are in the (175 - 119) papers that aren't in
literature.json?  Is our rate-limiting step (a) failing to recognize the
variants in the papers we crawl, or (b) not crawling the paper that
mentions the variant in the LOVD truth set?

**Comment by rcurrie** [comment]
@melissacline @amycoffin Very preliminary LOVD stat:

175 papers in LOVD of which 117 are in literature search

Per paper % variants found for papers common to both:

mean=0.75, variance=0.13

**Comment by rcurrie** [comment]
@melissacline @amycoffin @maximilianh 

Histogram of % variants found per LOVD paper:

![image](https://user-images.githubusercontent.com/492570/51062228-0476db80-15ab-11e9-91d8-0cae17607f60.png)

Fails (< 0.1 found):
['15353005', '17899372', '24667779', '18712473', '10638982',
       '14513821', '24395671', '12759930', '16280041', '11185744',
       '19423647', '18694767', '12442171', '22144684', '21673748']

**Comment by maximilianh** [comment]
What is your interpretation of this? Does the last bar mean "everything was
found" ?

You could also create a table with PMID, number of variants in LOVD, number
of variants found by pubMunch (pretty sure that Audrey has this already),
variants not found by pubMunch. Then someone could go over a handful of
variants and check why they weren't found. But I'm pretty sure that that's
covered in Audrey's report. That was pretty much the topic of her project,
I believe.

**Comment by rcurrie** [comment]
Correct - right bar at 1.0 means 100% of the variants in the LOVD set for a given PMID were found.

I’m encouraged by this histogram. I’m starting to looking into the handful on the far left...

**Comment by rcurrie** [comment]
@maximilianh @diekhans @amycoffin @melissacline 

I've cooked up a [stats report](https://nbviewer.jupyter.org/github/BRCAChallenge/pubMunch-BRCA/blob/master/stats.ipynb) on the current production literature search data with the basic LOVD comparison. I've made the artifacts (not the actual papers) available via my public_html so that you can click on 'open in colab' to run yourself and explore. Feedback welcome - or improve it directly in colab and share back :-)

**Comment by maximilianh** [comment]
Thanks! comparisons often include typical classification measures, like
accuracy, precision, sensitivity, specificity, etc. these tell you how many
% of the true variants were found, how many % were not found, how many %
were found that were not in LOVD, etc. But I think we have that in Audrey's
report, so maybe we don't need it anymore.

I don't know what the histogram is telling is, does it tell me that for
many papers all variants were found?

Hmm... something similar may also be interesting: a plot with the number of
variants in the paper on the x and the % of found variants on the y could
show if there is a link between the number of variants in the paper and the
recall?

Also possibly the %recall and the year maybe? I wonder if older papers are
less reliable sources.

From your data, can you extract a list like, (pmid, expectedVariants,
foundVariants, notFoundVariants, linkToPaper). In this format, someone
could go and try to figure out why a given variant wasn't found...

**Comment by melissacline** [comment]
Considering how PubMunch manages to crawl 83% of the papers overall, but 117/175 = 67% of the LOVD truth set, there might be something about the older papers.  For most of the 175 - 117 = 58 papers not crawled, the error was invalidPdf, which Max says probably means no access.  So that's one thing.

The LOVD truth set gives us a limited view of precision.  The false positives will include both bona fide false positives and genuine hits that weren't selected by the curators (e.g. papers that mention the variant briefly).  Still, it's instructive to see just what the precision (and recall) numbers look like overall.   It sounds like we're getting 750/1044 of the variants overall, so the recall could be improved, but is looking better than what Audrey had reported.  

I'll do a bit of spelunking on some of the PMIDs where we're hitting 0 variants, and see what I can see...

**Comment by maximilianh** [comment]
I guess this is obvious, just want to state that we should completely
separate the crawling success from the extraction success. They should be
treated as two separate problem. We only compare LOVD with pubMunch on
PMIDs that were crawled successfully. When I talk about extraction, then I
mean "for PMIDs that we crawled". The crawling is a separate problem that
needs no analysis.

**Comment by diekhans** [comment]
If you want to increase the download rate, it is worth actually looking
that the details of the particular failures.  I was able to fix a lot of
cases fairly easily this way.

**Comment by melissacline** [comment]
@maximilianh Thank you for the reminder on that!

In the spirit of separating the two issues, I looked the papers we haven't been able to crawl, and what journals they were.  Here is the breakdown by reported error.  The numbers in parentheses are the numbers of PMIDs from the LOVD set.

**Invalid PDF**
Am J Med Genet (1)
Fam Cancer (2)
Lancet (1)
Hum Mutat (17)

**HighwirePdfNotValid**
j. Clin Oncol (2)
Cancer Epidemiol Biomarkers Prev (1)

**HTTP Error** (for completeness)
PLoS Compbio (1)
Human Genet (1)

**No Crawler Success**
Int J Oncol (1)
Mol Biosyst (1)
Oncol Rep. (1)

So that explains why we're crawling fewer papers in the LOVD truth set - many are published in Human Mutation (which makes sense).  Human Mutation is published by Wiley.  FWIW, some of the articles we're not crawling are also in PMC.  @maximilianh would you expect us to be able to crawl Human Mutation?

**Comment by maximilianh** [comment]
Wiley has subcontracted bot detection to a company that is very good at it.
I used to have a working crack of that system but it stopped working. It
certainly could be made to work in some or another.

**Comment by melissacline** [comment]
All the things I've been learning this weekend!  Besides learning that it's time for me to get better at pandas and Jupyter notebooks (thanks, @rcurrie), I have useful results!

For the grant proposal, I did some analysis on the recall we're seeing in LOVD truth set.  In contrast to Rob's histogram, which describes the number of expected variant hits per PMID, this describes the number of expected PMID hits per variant.  In 750 out of 1045 variants, we have at least one hit in literature.json.  The remaining 295 variants are interesting, because it implies that the crawler isn't recognizing them.  52 are indels (which point back to the issue raised in user feedback, and 181 are intronic!  So, getting the indels working will help, but our bigger rate-limiting step are the intronic variants.

Here's a comparison of our performance to LitVar, NCBI's tool.  As @maximilianh said so truthfully, comparisons with LitVar are valuable!  Note that these results omit variants that neither we nor LitVar can interpret (there is a high overlap).  Also note that this conflates the two questions of 'can we parse the paper?' and 'can we find the variants in the paper?'.  

![histogram of recall per variant on the curated lovd dataset](https://user-images.githubusercontent.com/1714823/52540072-58a3e580-2d3a-11e9-9594-8c2a434a3ff6.png)

I looked at the variants for which we're getting zero recall on the truth set, but have found in other papers.  These are likely the ones for which we're not getting the papers from the journal.  These are 179 variants, that are mentioned in 28 papers collectively in the truth set:

08531967 OR 09523200 OR 09971877 OR 10506595 OR 10638982 OR 11389159 OR 11504767 OR 11877378 OR 12531920 OR 12552570 OR 12601471 OR 12955716 OR 14647443 OR 15876480 OR 16280041 OR 17279547 OR 17899372 OR 17924331 OR 18375895 OR 18680205 OR 18694767 OR 18824701 OR 19043619 OR 19287957 OR 20054658 OR 20513136 OR 21673748 OR 21741379
That's the PubMed query to get all of them.  It returns an assortment of journals:
Exp Cell Res 1
Eur J Hum Genet 1
Hum Mutat 5
Fam Cancer 1
Int J Oncol 1
Cancer Inform 1
J Clin Oncol 1 
Mutat Res 1
Am J Hum Gene 1
Breast Cancer Res Treat 1
Breast Cancer Res 1
Cancer Lett 1
Oncogene 1
Hum Genet 1
Proc Natl Acad Sci 1
Genes Dev 1
J Natl Cancer Inst 1
J Med Gene 1
Br J Cancer 1
J Clin Oncol 1
Hum Mol Genet 1
Genes Chromosomes Cancer 1
N Engl J Med 1
And it includes some older publications.  For instance, that NEJM article was published in 1996.

**Comment by melissacline** [comment]
For those older papers, we must be using the wrong version of the reference sequence.  NM_007294.3 and NM_000059.3 didn't exist yet in 1996.  As @diekhans has pointed out, the earlier reference sequences probably had smaller 5' UTR regions, which would throw off the sequence numbering.  So one more thing to add to the list is to figure out some logic to select the version of the reference sequence that matches the date of publication.

**Comment by rcurrie** [comment]
@melissacline  [This notebook](https://nbviewer.jupyter.org/github/BRCAChallenge/pubMunch-BRCA/blob/master/stats.ipynb) walks through all the artifacts (I've made them all accessible via public_html) such as which articles were able to be downloaded etc... Should be able to open in colab (click at the top). Jupyter + Pandas + Numpy + Lambda the Ultimate

PMIDs missing from the download list (don't have BRCA in title or abstract):
09805131, 12900794, 08942979, 08896551, 09333265, 08751436, 09971877, 09497265, 07939630, 09523200, 09126734, 19150617, 18415037, 08531967, 09585599, 2010, 07545954

Tried and failed to download:
18375895 (HighwirePdfNotValid), 15300854 (invalidPdf), 20020529 (invalidPdf), 12955719 (invalidPdf), 12601471 (httpError), 16528612 (invalidPdf), 15533909 (HighwirePdfNotValid), 12955716 (invalidPdf), 16786532 (invalidPdf), 16211554 (invalidPdf), 12552570 (invalidPdf), 10506595 (HighwirePdfNotValid), 11385711 (invalidPdf), 18693280 (invalidPdf), 19287957 (noCrawlerSuccess), 12815598 (invalidPdf), 17657584 (invalidPdf), 10406662 (invalidPdf), 18680205 (invalidPdf), 20054658 (invalidPdf), 17305420 (httpError), 17279547 (invalidPdf), 16969499 (noCrawlerSuccess), 16619214 (invalidPdf), 18493658 (noCrawlerSuccess), 20513136 (invalidPdf)

Diving down into the missing [ones from that bug report](https://github.com/BRCAChallenge/pubMunch-BRCA/issues/10) I'm thinking I need to be less conservative about the matching. The current production literature.json only matches if the normalized hgvs matches exactly:

In the case of 185delAG varFinder doesn't find any other information so I fail to normalized.
Solution: If nothing else works I'm going to look for this in the synonyms. This one only matches one so that will solve it, but we also may end up with some false matches...

In the case of 6174delT, varFinder correctly annotes this to NM_000059.3:c.6174delT which normalizes into NC_000013.11:g.32340529del. BUT, the BRCA Exchange database lists this as chr13:g.32340526:AT>A which normalizes to NC_000013.11:g.32340526_32340528delinsA via the hgvs library...
Solution: Look for the normalized HGVS in synonyms...except...built has '.' separating the transcript and g but the standard has ':'...

I'm working on this more liberal matching logic but so that if the conservative works I use that...

**Comment by diekhans** [comment]
This case
> chr13:g.32340526:AT>A which normalizes
> to NC_000013.11:g.32340526_32340528delinsA via the hgvs library...

might be a bug in the library, as HGVS defines delins as a
combination of dissertations and deletions, (or appears to,
depending on how one reads the very confusing text).

Contact Reece about this.

**Comment by amycoffin** [comment]
@diekhans @rcurrie I found a similar issue to what Mark is describing with this variant, which I think might be a combination of bugs:

chr17:g.43124146_43124147:dup

I couldn't find it in BRCA Exchange but it might be an issue with me not being able to track down the correct, unnormalized alias.

**Comment by rcurrie** [comment]
> This case
> chr13:g.32340526:AT>A which normalizes to NC_000013.11:g.32340526_32340528delinsA via the hgvs library...
> might be a bug in the library, as HGVS defines delins as a combination of dissertations and deletions, (or appears to, depending on how one reads the very confusing text). Contact Reece about this.

@diekhans this turns out to be my code that is doing the conversion from BRCA Exchange's primary key...not Reece's error.

**Comment by rcurrie** [comment]
I'm testing using a different column form the BRCA Exchange list of variants as input to the HGVS library toward generating a canonical genomic HGVS to use when matching mentions. Specifically the pyhgvs_cDNA field. Out of 21695 I'm getting ~100 that fail to map.

@zfisch @melissacline Is this a solid field to use?
@diekhans any comments on these failing ie a general class?

Net of these this may be a stronger anchor then my prior manual approach using pyhgvs_Genomic_Coordinate_38.

Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-1193C>T
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-1122T>C
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-1027C>A
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-1017T>C
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-924C>A
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-869G>A
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-845delA
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-764A>G
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-700T>G
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-672C>G
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-630G>T
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-592G>C
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-521delG
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-495G>A
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-481G>A
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-418A>G
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-407G>A
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-395C>T
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-357T>C
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-296C>T
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-280delG
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-268C>G
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-251G>A
Failed to parse: NM_000059.3:c.276_317-722del5070ins4
Failed Mapping: (HGVSInvalidVariantError): NM_000059.3:c.595_6539del14318
Failed Mapping: (HGVSInvalidVariantError): NM_000059.3:c.6418_7419del14500
Failed Mapping: (HGVSInvalidVariantError): NM_000059.3:c.7397T>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.4358-1513_*37600del70050
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.5406+664_*8273del11053
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*6207C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*5860C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*5677_*5678dupAT
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*5513G>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*4549G>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*4271T>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*4056C>A
Failed to parse: NM_007294.3:c.5468-285_*4016del4426ins2
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*3785T>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*2810A>G
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*2670A>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*2602C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*1984C>G
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*1922T>C
Failed to parse: NM_007294.3:c.5213_5278-2753del3247ins1
Failed Mapping: (HGVSInvalidVariantError): NM_007294.3:c.4987_5277del10644
Failed to parse: NM_007294.3:c.5152+149_5193+2200del2593ins12
Failed to parse: NM_007294.3:c.1878_2126del249ins2
Failed to parse: NM_007294.3:c.442-952_547dup1058
Failed Mapping: (HGVSInvalidVariantError): NM_007294.3:c.133_136del9196
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-31665_81-4067del37071
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-33026_80+3829del38090
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-264T>G
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-273G>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-287C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-315delT
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-366C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-371G>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-378C>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-380G>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-408T>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-497G>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-516A>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-577A>G
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-585C>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-589A>G
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-593T>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-676T>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-728A>G
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-730C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-848A>G
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-932T>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-939C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-946G>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-948G>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-1044C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-1074C>G
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-1109C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-1457G>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-1465G>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-1619G>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-1648T>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-1959C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-2030T>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-2261T>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-2266G>A
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-2293C>G
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-2502T>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-2569G>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-2614T>C
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-2617_-2616delGT

**Comment by melissacline** [comment]
That sounds very encouraging!  One question, when you say that about a
hundred of the 21695 fail to map, what is this 21695?  Are these the
variants currently in BRCA Exchange?  One thing I notice is that the
exception cases include many with large negative offsets, which might fall
beyond the gene boundaries.

**Comment by diekhans** [comment]
Failed Mapping (HGVSInvalidIntervalError): NM_000059.3:c.-1193C>T
Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*6207C>T

  The `c' HGVS are a bit weird.  My understanding is that these
  are the location in the genome relative to the coding DNA bases
  in the DNA.

  These slides do a pretty good job of explaining it:
     http://www.hgvs.org/mutnomen/ESHG2007_W12_JdD.pdf
  The HGVS spec itself is hard to read.

  The c.- are 5' of the annotated start codon (probably first
  base) and c.* are 3' of stop codon (presumably the last base).

  It appears that these are not support by the library.

  Even if they were supported, these raise the issue of which
  genome assembly was used.  Be glad you are working with very
  well studied and stable gene annotations.  In the general case,
  you have the problem that the refseq version number on reflects
  changes in the sequence, not the annotation of the start and stop
  codons.  Moving the chosen start codon is a rather common think
  annotators do based on new evidence.
  
Failed to parse: NM_000059.3:c.276_317-722del5070ins4
Failed to parse: NM_007294.3:c.5213_5278-2753del3247ins1

  These looks like an attempt to encode both a deletion and
  insertion in one hgvs string.  I am not sure this is legal.

> Failed Mapping: (HGVSInvalidVariantError): NM_000059.3:c.595_6539del14318
> Failed Mapping: (HGVSInvalidVariantError): NM_000059.3:c.6418_7419del14500

  No idea what is going on here

Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.*5677_*5678dupAT

  OMG

Failed Mapping (HGVSInvalidIntervalError): NM_007294.3:c.-2617_-2616delGT

  WTF

**Comment by rcurrie** [comment]
@melissacline Yes, 21695 are the variants from the latest built tsv is all the ones we have curated.

**Comment by zfisch** [comment]
@rcurrie pyhgvs_cDNA is a solid field to use -- it's where we derive the pyhgvs_Genomic_Coordinate_XX fields from (https://github.com/BRCAChallenge/brca-exchange/blob/master/pipeline/data_merging/brca_pseudonym_generator.py#L165).

Am I understanding correctly that using pyhgvs_cdna instead of pyhgvs_genomic_coordinate produces different results? if you're using counsyl's pyhgvs library to form canonical hgvs, it really seems like either input should produce the same result...

**Comment by rcurrie** [comment]
@zfisch In the current production version I was creating a genomic hgvs synthetically from the chrome, pos etc.. fields as pyhgvs_Genomic_Coordinate_XX isn't canonical. I'm going to switch to pyhgvs_cDNA for this next version.

**Comment by rcurrie** [comment]
I've generated a preliminary literature.json using the new matching algorithm. Not validated yet as for some reason a few of the founder mutation articles are not getting matched correctly, but it appears to have improved our LOVD hit a bit:

![image](https://user-images.githubusercontent.com/492570/52903203-f716c780-31ce-11e9-9bd4-d0db101f2030.png)

Once I sort out making sure the articles are in score order and resolve the founder articles I'll do an updated crawl and generate a new literature.json to put onto beta. The matching now takes much much longer but primarily because I haven't really optimized the pandas fu in it.

**Comment by melissacline** [comment]
Wow, fingers crossed!

**Comment by rcurrie** [comment]
Including hits in all three categories (hgvs mapped matches, hgvs matches a synonym, text matches synonym):
![image](https://user-images.githubusercontent.com/492570/53131855-cf9f6200-3522-11e9-80f0-57efd0677bbf.png)

Bad news - false positive rate way up (not surprising):

```
Current Production Confusion Matrix:
1094	1237
675	0

New Confusion Matrix w/Synonym Match:
1131	7539
665	0
```
I'm going to re-run but by skipping text to synonym if either of the first two matches work.

@melissacline @maximilianh Forgive my statistical feebleness but I'm struggling to sort how to count true negatives. The above matrices are computed via the following logic:

Sum the following for each paper that is in the LOVD truth set that we were also able to download

True Positive = intersection of found variants to true variants
False Positive = found variants minus true variants
False Negative = true variants minus predicted variants
True Negative = ?

**Comment by melissacline** [comment]
I was also thinking about what true negatives are in this context.  The
literal definition is the universe of variants that are accurately
predicted as not mentioned in the paper.  This number would dwarf all
others.  We can avoid the whole issue by sticking with precision (TP/(TP +
FP)) and recall (TP/(TP + FN))

Thinking about the spike in false positives, I'm guessing that the variant
identifiers are truly there in the text (the ones that match on synonym
matches), but are getting combined with incorrect gene/transcript
identifiers to produce those false positive hits.  If that's true (how
could we check if that's true?  Spot-check some false positives?), then it
may be time to resume that conversation with Max and Mark about alternative
strategies.  Max has had some ideas.

**Comment by rcurrie** [comment]
Update: Spent many hours trying various approaches to get some portion of the founder papers without resorting to raw search of the text in the synonyms and hence the high false positives. Not there yet but at the moment:
```
Current Production 
Confusion Matrix:
1094	1237
675	0
Precision: 46.9%
Recall: 61.8%

Latest w/o Synonym Match
Confusion Matric:
1127	1194
722	0
Precision: 48.6%
Recall: 61.0%
```

**Comment by rcurrie** [comment]
Latest approach:
Don't try and map everything back to genomic coordinates. There is just too much variability when going from coding to genomic. We also have fairly well curated synonyms in coding space so purely parsing the hgvsCoding from the crawler and then seeing if we get a direct match to pyhgvs_cDNA (score = 1), if not a synonym (score = 2), and then falling back to searching the raw text in synonyms but only if the text is >= 6 characters long (score = 3).

Within a subset crawl of all LOVD papers + Founder Papers:

Matches with score 1: 3627 2: 3786 3: 2391

![image](https://user-images.githubusercontent.com/492570/53245808-ae925a80-3663-11e9-9e38-33edff985da2.png)

```
Current Production
Confusion Matrix:
1094	1237
675	0
Precision: 46.9%
Recall: 61.8%

New
Confusion Matrix:
1166	2242
697	0
Precision: 34.2%
Recall: 62.6%
```

This also gets 99% of the founder papers bug report. This plus ordering by score may do the trick as good hits will be at the top, but if there is nothing good (for example a few of the founder papers) then the pure text in synonym will be at the top, possibly a false positive but sort of like page 5 in google...

**Comment by melissacline** [comment]
Encouraging!  What I've heard from our users suggests that 34% precision
doesn't worry them, esp. if we can manage to down-rank the weaker hits and
have stronger precision near the front of the list.

**Comment by rcurrie** [comment]
Closing as now part of standard stats for each release notebook.

**Comment by maximilianh** [comment]
Sorry what does this mean, “release notebook” ?

**Comment by rcurrie** [comment]
I have a 'stats' notebook that has some ~unit tests against LOVD and founder mutations:

https://github.com/BRCAChallenge/pubMunch-BRCA/blob/master/stats.ipynb

See the very bottom for precision and recall.

**Comment by diekhans** [comment]
Would it be possible to convert the notebook to actual unit
tests; perhaps with pytest?  I would require some kind of fuzzy
checking. However, pubmunch could really use `make test' to do
much more validation.

**Comment by rcurrie** [comment]
Eventually yes. We made a big upgrade to the results via much more fuzzy matching in the latest release. My near term plan is to get the pubMunch merged and then work on better tooling (integrated basic test, docker that anyone can run) so we can have results monthly. Will file another issue to track a unit test @diekhans

**Comment by maximilianh** [comment]
Yes, some automated testing would be great. There are two types of tests:

- test the crawler: given a list of PMIDs, check that we got similar
enough text files back.

- test the variant/gene finder: given a list of text files, check that
we get the identical genes and variants.
